### ISSUE TITLE
gitter im

### ISSUE THREAD

**Issue by hhirsch** [OpenSFNovels/opensfnovel01#12]
I just tried to create a gitter account for the repository but it does not show up in my public repos https://gitter.im

**Comment by jrmiller82** [comment]
Is that a permissions issue on my end? I'll look into it tomorrow. I couldn't manage your permissions until you accepted the organization invite and now I'm in bed. :)

**Comment by jrmiller82** [comment]
You have admin permissions on this repo now. See if that works now.

**Comment by hhirsch** [comment]
@jrmiller82 I don't have the permission to add this repo to gitter. You should have received a mail that prompts you to add the permission.

**Comment by jrmiller82** [comment]
@hhirsch I think I fixed it. I added it to the allowed apps for the organization. I should be able to look at it more this evening. What does it do?

**Comment by hhirsch** [comment]
@jrmiller82 It is a chat so that we don't have to communicate through issues all the time.

**Comment by jrmiller82** [comment]
@hhirsch Great. I 'authorized' it through the organization panel.
Apparently Github changed all the settings in October 2015 so sometimes the
third party vendors haven't updated their APIs.

Also, if you're ever on irc.freenode.org, I'm on IRC a bunch.

--
James Ryland Miller
Law Office of James Ryland Miller, PLLC
jrm@lawjrm.com; (817) 840-7743 <+18178407743> voice; (817) 200-7637 fax
1325 W. Randol Mill Rd, Ste V201, Arlington, TX 76012
By appointment only.
www.lawjrm.com

**Comment by hhirsch** [comment]
@jrmiller82 I am there most of the time in ##glportal . Where are you?

**Comment by unstoppablecarl** [comment]
How do I get access to the gitter channel?

**Comment by hhirsch** [comment]
@unstoppablecarl I was unable to create it. The create button on the gitter page just does nothing. And I can not add our repository it seems @jrmiller82 has to do that.

**Comment by jrmiller82** [comment]
I have added the permission for gitter. Please try again.

**Comment by jrmiller82** [comment]
Frankly, this gitter thing is horrible; their interface is broken, their request for permissions is horrible.. I think with the github API reconfigure in October, they haven't updated their own software. It's authorized in github in three different settings, and still won't let me create a room or anything.

**Comment by jrmiller82** [comment]
https://gitter.im/OpenSFNovels/pub is a public room. For the organization only room, it says there are no organization members other than me.
