### ISSUE TITLE
Style: Hard or Soft wrap lines? Line width? One-line per sentence? 

### ISSUE THREAD

**Issue by jrmiller82** [OpenSFNovels/opensfnovel01#13]
Are we wanting to wrap lines or not? I'm usually editing in emacs or vim so I tend to hard wrap. But, it may make sense to do one sentence per line when we start writing as it will make diffs easier to read. Although git does have word diffs built in. 

Thoughts?

**Comment by unstoppablecarl** [comment]
I think line breaks should denote the end of a paragraph. Keep it simple and familiar.

**Comment by jrmiller82** [comment]
@unstoppablecarl I disagree that line breaks should denote end of paragraphs. I think a blank line should denote end of a paragraph since we're writing in org-mode. We're using org-mode to make latex and html export trivial for the end product of the novel.

**Comment by jrmiller82** [comment]
I'm willing to hard wrap or soft wrap an entire paragraph if that means @unstoppablecarl comes back! :)

**Comment by hhirsch** [comment]
@jrmiller82 I agree with your reasoning because org-mode.

**Comment by jrmiller82** [comment]
The one sentence per line? Or the wrapping?

**Comment by hhirsch** [comment]
@jrmiller82 All for hard-wraps.

**Comment by jrmiller82** [comment]
I always forget that git will do a word diff. Confession: I tend to use mercurial for my single user personal repos instead of git. :)

So, hard wrapped paragraphs, NOT one sentenc per line, with a blank line indicating the end of a paragraph?

**Comment by hhirsch** [comment]
I tend to just wrap it after x chars so that it looks good in a terminal. When cating the file or editing it in the text terminal. For a paragraph I leave an empty line.

**Comment by jrmiller82** [comment]
Ok. **Hard line wraps with a blank line for paragraph separation.**
